name: Build and Push Docker Image

on:
  push:
    branches:
      - feature/docker-containers

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine version tag
      id: get_tag
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          if [ -z "${{ github.event.inputs.custom_tag }}" ]; then
            echo "tag=manual-build" >> $GITHUB_ENV
          else
            echo "tag=${{ github.event.inputs.custom_tag }}" >> $GITHUB_ENV
          fi
        elif [ "${{ github.event_name }}" == "push" ]; then
          latest_release_tag=$(curl -s https://api.github.com/repos/testwl12/actionstest/releases/latest | jq -r .tag_name)
          echo "tag=${latest_release_tag}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./node-app/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ env.tag }}
        labels: |
          org.opencontainers.image.source=https://github.com/testwl12/actionstest
          org.opencontainers.image.description="My container image 2"
          description="Another description"
          org.opencontainers.image.licenses=MIT
